// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGm1tJhpHeBaNkKxhGZ8zEhSwo8pzQg4E',
    appId: '1:346088569639:web:eec0ae72e89aa3dc1ec702',
    messagingSenderId: '346088569639',
    projectId: 'floria-5b884',
    authDomain: 'floria-5b884.firebaseapp.com',
    storageBucket: 'floria-5b884.appspot.com',
    measurementId: 'G-EXFVXMP239',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXSXnd2BB9U2baj-Sf3NPprfCalj1A_Hk',
    appId: '1:346088569639:android:c9284d34ac5f73311ec702',
    messagingSenderId: '346088569639',
    projectId: 'floria-5b884',
    storageBucket: 'floria-5b884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTlZ5v2VjEUZyh5IbBZhar0TcP9uuZinY',
    appId: '1:346088569639:ios:114d001866e335561ec702',
    messagingSenderId: '346088569639',
    projectId: 'floria-5b884',
    storageBucket: 'floria-5b884.appspot.com',
    iosBundleId: 'com.example.floria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTlZ5v2VjEUZyh5IbBZhar0TcP9uuZinY',
    appId: '1:346088569639:ios:c9485093046a722b1ec702',
    messagingSenderId: '346088569639',
    projectId: 'floria-5b884',
    storageBucket: 'floria-5b884.appspot.com',
    iosBundleId: 'com.example.floria.RunnerTests',
  );
}
